{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#from geojson import FeatureCollection\n",
    "import geopandas\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "url_coral_reef = \"https://opendata.arcgis.com/datasets/9229d814438349948c99b5e61a084418_7.geojson\"\n",
    "\n",
    "#my_feature = FeatureCollection(url_coral_reef)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 76: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 81: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 72: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1934, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'UnicodeDecodeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 1936, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n",
      "Exception ignored in: 'fiona._env.log_error'\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\Programas\\anaconda3\\envs\\ocean_haz\\lib\\site-packages\\fiona\\env.py\", line 289, in defenv\n",
      "    local._env.start()\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 71: invalid continuation byte\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<AxesSubplot:>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAVYAAAD4CAYAAAC3zs6pAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAsuUlEQVR4nO3de3yU1bno8d8zt1xIQIUEETARxQuQQAAhHgXxgiLe67HVdlNPrbKV4uXsXY/u0xvbrS1H/bRWy/4oG61oKcUb3VK1GlFELSoEAygoioIigQSQEMhlbs/5YyYxIZNkZjKTmSTP9/PJJzPvrPd918okT9asd73PElXFGGNM4jhSXQFjjOltLLAaY0yCWWA1xpgEs8BqjDEJZoHVGGMSzJXqCkQyaNAgLSwsTHU1jDEmovLy8r2qmtfe62kZWAsLC1m3bl2qq2GMMRGJyI6OXrehAGOMSTALrMYYk2AWWI0xJsHScozVmJ7A5/Oxc+dOGhoaUl0VkySZmZkMGzYMt9sd034WWI2J086dO8nNzaWwsBARSXV1TIKpKvv27WPnzp2ccMIJMe1rQwHGxKmhoYGBAwdaUO2lRISBAwfG9YnEAqsxXWBBtXeL9/21oQBjusnBBh8vb6qk6mAj+f0zuKhoCP0zYxu7Mz1DnwysvoAPb8DLgcYDHJN1DFmuLA55DwHwec3nHGg8wIT8CfTz9EtxTU1v8YfXP+U/V22jzhto3vbvKzYzZ9qJzD13ZAprZpKhTw4FuJ1u+nn6MTR3KBnODLwBLy6HixxPDsV5xUwdNpVsd3Zz+QMNB/j60NfUNNaksNamp/rD65/ywKtbWwVVgDpvgAde3cofXv807mPv3r2ba665hhNPPJFRo0Yxc+ZMtm7d2tUqA6E7IPfu3ZuQY7X01ltvMXr0aMaNG0d9fX3U++Xk5CS8LsnSJwNrSw5x4HF6yHRlttrecmzlqMyjGJozlFx3bndXz/RwBxt8/OeqbR2W+c9V26ht8MV8bFXlyiuvZNq0aWzbto3Nmzfz61//mj179kS1fyAQ6LxQEo6xZMkSfvrTn1JRUUFWVlaX65CO+nxgjYXDEfpxBYJd/4U0fcPLmyrb9FSPVOcN8PKm3TEf+4033sDtdnPTTTc1bxs3bhxTpkxBVbnjjjsYM2YMRUVFLFu2DIBVq1Zxzjnn8P3vf5+ioiIArrjiCiZMmMDo0aNZuHBhp+fNycnhl7/8JZMnT2bNmjX86U9/YtKkSYwbN45//ud/bg62r776KmeccQbjx4/n6quv5tChQyxatIinn36au+++mx/84AdUVlYydepUxo0bx5gxY3jrrbc6PPfPfvYzxo4dS2lpafM/kBUrVjB58mRKSko4//zzm7cXFRVx4MABVJWBAwfy5JNPAjBr1ixee+01tm/fzpQpUxg/fjzjx4/nH//4R4zvQPt6bWD1BXz4ArH3AqLxZe2XSTmu6X2qDjZGV6429ik9H374IRMmTIj42vPPP09FRQUbNmzgtdde44477qCyshKA999/n3vvvZfNmzcD8Pjjj1NeXs66det46KGH2LdvX4fnPXz4MGPGjOG9995j4MCBLFu2jHfeeYeKigqcTidLlixh79693HPPPbz22musX7+eiRMn8tvf/pYbbriByy67jPvvv58lS5bw5z//mQsvvLC5ruPGjevwvKWlpWzYsIGpU6fyX//1XwCcddZZvPvuu3zwwQdcc8013HfffQCceeaZvPPOO3z00UeMGDGiOWi/++67lJaWkp+fT1lZGevXr2fZsmXceuutMf38O9IrL141+BrIcGUkbSrM0JyhSTmu6X3y+2dEVy43s/NCMXj77be59tprcTqdDB48mLPPPpu1a9fSv39/Jk2a1GrC+0MPPcTy5csB+Oqrr/j0008ZOHBgu8d2Op1cddVVAKxcuZLy8nJOP/10AOrr68nPz+fdd99l8+bNnHnmmQB4vV7OOOOMNsc6/fTTuf766/H5fFxxxRUdBlaPx8Mll1wCwIQJEygrKwNCN2p873vfo7KyEq/X29y2KVOmsHr1agoKCrj55ptZuHAhX3/9Nccccww5OTnU1NQwd+7c5n8IiRqbhl7aY1XRpM4v9Dg9STu26V0uKhpCtsfZYZlsj5OLio6N+dijR4+mvLw84msdrb7cr9+3s11WrVrFa6+9xpo1a9iwYQMlJSWdTojPzMzE6XQ2n+e6666joqKCiooKPvnkE+bNm4eqMn369Obtmzdv5rHHHmtzrKlTp7J69WqGDh3KrFmzmj+uR+J2u5v/rp1OJ36/H4BbbrmFuXPnsmnTJh599NHm+k+dOpW33nqLt956i2nTppGXl8ezzz7LlClTAPjd737H4MGD2bBhA+vWrcPr9XbY7lj0ysCa5eqdA+Km5+mf6WbOtBM7LDNn2onkxjGf9dxzz6WxsbH5IzHA2rVrefPNN5k6dSrLli0jEAhQXV3N6tWrmTRpUptj1NTUcPTRR5Odnc3HH3/Mu+++G1MdzjvvPJ599lmqqqoA2L9/Pzt27KC0tJR33nmHzz77DIC6urqIPcIdO3aQn5/PjTfeyI9//GPWr18f0/mb2jB0aOhT5OLFi5u3Dx8+nL179/Lpp58yYsQIzjrrLB544IHmwFpTU8OQIUNwOBw89dRTCbmY16RXBlZj0sncc0fy0wtObtNzzfY4+ekFJ8c9j1VEWL58OWVlZZx44omMHj2aefPmcdxxx3HllVdSXFzM2LFjOffcc7nvvvs49ti2veIZM2bg9/spLi7mF7/4BaWlpTHVYdSoUdxzzz1ccMEFFBcXM336dCorK8nLy+OJJ57g2muvpbi4mNLSUj7++OM2+69atYpx48ZRUlLCc889x2233Rbzz2HevHlcffXVTJkyhUGDBrV6bfLkyZx88slAaGjg66+/5qyzzgJgzpw5LF68mNLSUrZu3dqqJ99V0tFHhlSZOHGixrOCgGpyhwAAghpke812Rhw1IqnnMelvy5YtnHbaaVGXr23w8fKm3VTVNpCfm8lFRcfG1VM13SvS+ywi5ao6sb19es3FK2/A2y1jnxVVFRQNKkr6eUzvk5vp5runD091NUw36DSwishw4EngWCAILFTV34vI/cClgBfYBvxIVQ9E2H8G8HvACSxS1fmJq373qqqroqB/AW6n9TKMSZbJkyfT2Nh6mtpTTz3VPO+2J4imx+oH/lVV14tILlAuImVAGfBvquoXkf8H/BtwZ8sdRcQJLACmAzuBtSLygqpuTmgrACH5WYYaA40Mz7UehzHJ9N5776W6Cl3W6cUrVa1U1fXhx7XAFmCoqr6qqv5wsXeBYRF2nwR8pqqfq6oX+AtweWKq3prLkfxRjQxndHMSjTF9W0yzAkSkECgBjvyXcj3wcoRdhgJftXi+M7wt0rFni8g6EVlXXV0dS7Wa9o95n1jlZbW7jLgxxjSLupsnIjnAc8DtqnqwxfafERouWBJptwjbIk5DUNWFwEIIzQqItl7dyZIam66o9dZStqOM6rpq8rLzmF4wnVyPJfbpjaIKrCLiJhRUl6jq8y22XwdcApynkedt7QRaDkoOA3bFX93oHPYd5pP9n5DtzmZg5kDysq2naVJr4caFLNq0iHr/t2ny5r8/nxuKbmB28ewU1swkQ6dDARLqpj0GbFHV37bYPoPQxarLVLWund3XAiNF5AQR8QDXAC90vdod6+fux/jB4zn1mFPxOD1sr9me7FMa066FGxfy8AcPtwqqAPX+eh7+4GEWbuw8o1R7LB9reopmjPVMYBZwrohUhL9mAn8AcoGy8LZHAETkOBF5CSB8cWsu8Aqhi15Pq+pHyWhIewZkDOD4/sfT6I8uy5AxiVTrrWXRpkUdllm0aVHzChaxsHys6SuaWQFvq6qoarGqjgt/vaSqJ6nq8BbbbgqX36WqM1vs/5KqnqyqJ6rqvclsTHsc4kAjD+0ak1RlO8ra9FSPVO+vp2xHWczH7ov5WAH27t3LGWecwYsvvthuTtVVq1Y1Z8ICmDt3Lk888QQAd999N6effjpjxoxh9uzZHSasiVefyRVw5AoBxnSH6rroZrhU18c+E6av5WMF2LNnDxdffDF33303F198cVw5VefOncvatWv58MMPqa+v529/+1un+8Sq19zS2lXdkWfA9D3RXjhN9FS+3piP1efzcd5557FgwQLOPvvs5m2x5lR94403uO+++6irq2P//v2MHj2aSy+9tNP9YtFneqydsaBqkmF6wfRO01hmubKYXjA95mP3tXysLpeLCRMm8MorrzRvay+nqsvlIhgMNpdralNDQwNz5szh2WefZdOmTdx4442dtjceFliNSaJcTy43FN3QYZkbim4gxxP7Fe++lo9VRHj88cf5+OOPmT9/fnP9I+VULSgoYPPmzTQ2NlJTU8PKlSuBbwPsoEGDOHToEM8++2xM7Y2WDQUYk2RN81SPnMea5crq0jzWpnyst99+O/PnzyczM5PCwkIefPBBpk6dypo1axg7diwi0pyP9cicqDNmzOCRRx6huLiYU045pUv5WIPBIG63mwULFlBaWtqcj7Upoco999zTnBu1yapVq7j//vtxu93k5OR02GOF0DDEX/7yFy699FL69+/PnDlzuOqqq3jmmWc455xzmnvjw4cP57vf/S7FxcWMHDmSkpISAI466ihuvPFGioqKKCwsbB7CSLRelY/VmO4Uaz7WQ95DoTuv6qvJywrdeRVPT9V0rz6dj9WYdJfjyeHKkVemuhqmG1hgNcaklb6Sj9UYY7pNn8jHaowxJjYWWI0xJsFsKMAk1SGfn2yXE4fdgEFjvZ9t66uoq2kke0AGJ47PJyPL/gR7I3tXTcL5gkowGMQh0M8VukMnqNqng+u6l7ZT/soO/I3fZoN66+lPmXBhARNnFqauYiYpbCjAJNzOhkY8TgdupxMRCX2lulIptO6l7bz3wuetgiqAvzHAey98zrqXtsd97L6UjzVZ9UkGC6wmoQLBICdkZ7bJvSAiSUnPlu4a6/2Uv7KjwzLlr+zAW+/vsEwklo81fVlgNQnjDwZxOtr/laoPBPG1SIzRF2xbX9Wmp3okf2OAz9ZXxXzsvpqPtaM65+Tk8LOf/YyxY8dSWlra/E9mxYoVTJ48mZKSEs4///yo//nEywKrSYigKvXBjnuk2S4nzm6qT7qoq4lu5Yq6Gm/Mx+6L+VibtFfnw4cPU1payoYNG5g6dWpzgpqzzjqLd999lw8++IBrrrmG++67L6rzxMsuXpkuqwsE+cbnY2hmRqdlv6j3cnxWBm5H3xh1zR7Q+c8kVM6T0PP2xnysLbVXZ4/H07xywIQJEygrC63MsHPnTr73ve9RWVmJ1+tt1f5ksB6r6ZKGQIDGQCCqoApwQnYG3/j8BPrIeOuJ4/NxZXTcT3dlODlpfH7Mx+5r+VijqbPb7W4e33c6nfj9obHrW265hblz57Jp0yYeffTRpORgbckCq4maPxgkoEpQlWqvj4qDdeysbyTHFf0HH4cI+Rluth5O7i92usjIcjHhwoIOy0y4sABPHPNZ+1o+1q7UuaamhqFDhwKwePHiWJoYFwusJmouhwOnCA4R8jxuxvXP5qSc7Lg+1p/aL5N39tf2iZ7rxJmFTL5sRJueqyvDyeTLRsQ9j7UpH2tZWRknnngio0ePZt68eRx33HFceeWVFBcXM3bsWM4999zmfKxHmjFjBn6/n+LiYn7xi190KR9rcXEx06dPp7Kykry8vOZ8rMXFxZSWlrbJBQuh3ue4ceMoKSnhueee47bbbuv0nPHUed68eVx99dVMmTKFQYMGxdTGeHSaj1VEhgNPAscCQWChqv5eRK4G5gGnAZNUNWICVRHZDtQCAcDfUQ7DJpaPtW+oDwQ54PczJCOx44vdJdZ8rN56P5+tr6Kuxkv2AA8njc+Pq6dquley8rH6gX9V1fUikguUi0gZ8CHwHeDRKI5xjqr2jJm9pttkOR1kOXtmUI2HJ8vFqDOPS3U1TDfoNLCqaiVQGX5cKyJbgKGqWga2CJ8xJrH6XD5WESkESoBYEiYq8KqIKPCoqnY+A9kY02f1hnysUQdWEckBngNuV9WDMZzjTFXdJSL5QJmIfKyqqyMcfzYwG+D444+P4fCmOzQGg2R0cFeVMeZbUf2liIibUFBdoqrPx3ICVd0V/l4FLAfazvkIvb5QVSeq6sS8vLxYTmG6QYbDQWOgb92Oaky8Og2sEhpEfQzYoqq/jeXgItIvfMELEekHXEDoopfpgTKcDoLddK//YX+AGl/siUnSWbDBz+G1uzm48ksOr91NsKF3tc98K5qhgDOBWcAmEakIb/u/QAbwMJAHvCgiFap6oYgcByxS1ZnAYGB5+AKXC/izqv49wW0w3ai7Lla6HEI/R+/JLHDw9S+pXfUV6v32H9OBFdvInTac/ufa0Fdv02mPVVXfVlVR1WJVHRf+eklVl6vqMFXNUNXBqnphuPyucFBFVT9X1bHhr9Gqem+yG2SSS0S6ZVJ/b7pv4ODrX3Lw1R2tgiqAeoMcfHUHB1//Mu5j96V8rMlyww03NCekSRS7GmFi9o2v63k8O5PpdFBd30iwh0fYYIOf2lVfdVimdtVXcQ0LWD7WxFi0aBGjRo1K6DEtsJqYDfJ0z91CeVkZ7Gn0dcu5kqV+0942PdUjqTdI/abYe4Z9LR9rTk4Od955JxMmTOD888/n/fffZ9q0aYwYMYIXXngBgO3btzNlyhTGjx/P+PHj+cc//tHc7qasVwBz587liSeeAGDatGkk+k5PC6wmrQ1wu3p0PoHAwejyrAZqLR9rZ/lYDx8+zLRp0ygvLyc3N5ef//znlJWVsXz5cn75y18CkJ+fT1lZGevXr2fZsmXceuutMf9cE8FuVDZpLdvZs//3O/tHd8uuM9fysXaWj9Xj8TBjxgwAioqKyMjIwO12U1RUxPbt2wHw+XzMnTu3Ocgnarw5VhZYTdrb5/Ux0ONOdTXiklU0iAMrtnU4HCAeB1lFsWdcGj16NM8++2zE1+LJx5qdnc20adPiysf6m9/8plWZFStWMH36dJYuXdrhsZrysb744ovMmjWLO+64gx/+8IcRy7bMtepwOMjIyGh+3JR39Xe/+x2DBw9mw4YNBINBMjMzAXC5XK2mClo+VtNjVXt9rNx3kHe+qe3SRahcp5Ov6qNb4iTdODJd5E4b3mGZ3GnDcWRaPtZo87F2pKamhiFDhuBwOHjqqaeax3sLCgrYvHkzjY2N1NTUsHLlyi6dpzPWYzVdtrvRR2MwyJZDDexoaCTL4eDYDDd//Hov0wf25/pheagqdYEgX9U3sqG2nkvyj4r6Y77H6WB4VgZBVRw9MOlP0zzVI+exisfRpXmsTflYb7/9dubPn09mZiaFhYU8+OCDTJ06lTVr1jB27FhEpDkf65E5UWfMmMEjjzxCcXExp5xySpfysQaDQdxuNwsWLKC0tLQ5H2tTQpV77rmHk08+udX+q1at4v7778ftdpOTkxPVCgIdmTNnDldddRXPPPMM55xzTnPvfPjw4Xz3u9+luLiYkSNHUlJS0qXzdKbTfKypYPlYe5ZV+w/Sz+lkVE4mKPRzRTexv9rro84fpCC79bIuAVU21dYjwNj+2UmocWLEmo812OCnftNeArVenLkesooGxdVTNd0rWflYjenQtGP6x7VfnsfNXvy8d+AQk4/KIRAMsq2+kW98AQa4nexp8OENBvH0kuQvjkwX/U5vm8Xf9D4WWE1KDfK4qAu4WX/wMMMzPZzc79sJ46f2S/3kcdP9+lw+VmOS4fisDI7Pim6VV9P79YZ8rL3jM5YxxqQR67GaPk9VUVUccYzlqoau8ot0vq/fX0tV1cs0NlaRkZFPfv5FuFy5MZ/TpD8LrKbPE5Gkp0P8YvsCdux4hECgrnnb1k//g4KCmzih8CdJPbfpfhZYjemCaHqqX2xfwOeft80RHwjUNW+34Nq72Bir6bOCQT8+X3Lv6PL7a9mx45EOy+zY8Qh+f21cx7d8rNE5MrtVsllgNX1WIFCP253c2QhVVS+3+vgfuR51VFXFvrCG5WNNXxZYTZ/lcuUk/RyNjVXRlfNGV64ly8faNh9rQ0MDP/rRjygqKqKkpIQ33nijzXH279/PFVdcQXFxMaWlpWzcuDH6H3qULLCaPikQaIzqglUg0EDNwQ3s3fcm33zzHocOfUIwGH22/4yM/OjKeaIr15LlY22bj3XBggUAbNq0iaVLl3Lddde1yWT1q1/9ipKSEjZu3Mivf/3rdrNpdYVdvDJ9ksPhIRgMoOrD663C5zuIz7ePYLCRYNBLo7caNEhD427654Z6drX1m/D5a/D7ajj6mLNRLUBVOwzQ+fkXsfXT/+hwOMDpzCY/f0ZC29dX87G+/fbb3HLLLQCceuqpFBQUtBlzfvvtt3nuueeAUIawffv2UVNTw4ABA9o9d6wssJo+KTTFygk4yco6nliH+gKBBvbv+4RG7x4c4sbhyMDp7NcmyLpcuRQU3BRxVkCTgoKb4prPavlY2+ZjjSapVKQyiZ5uZ0MBxsTB6czE4fCQmXEsHs9AHI4MvN5qGhp209BQid9/mECgHp+vhuOG/E8KCm7C4cg64hjZjBjxL3FPtbJ8rG1NnTqVJUuWALB161a+/PJLTjnllHbLrFq1ikGDBtG/f3yJhNrTaY9VRIYDTwLHAkFgoar+XkSuBuYBpwGTVDVinj8RmQH8HnACi1R1foLqbkzacDjczeOpqgGCQS+BQD0ORwYZGYM56cQ7KCy4iaqqv9PorSLDk09+/ox2e6qdDTGA5WONZM6cOdx0000UFRXhcrl44oknmnu2TebNm8ePfvQjiouLyc7OZvHixV06ZySd5mMVkSHAEFVdLyK5QDlwBaCEAu2jwE8jBVYJfdbaCkwHdgJrgWtVtcNFvC0fq+kJYs3HGo1oAqrpXknJx6qqlUBl+HGtiGwBhqpqWfgEHe0+CfhMVT8Pl/0LcDnQYWA1pq9p6uBYUO0dYrp4JSKFQAkQbV6vocBXLZ7vBCa3c+zZwGyA44+Pb6kKY3oqDSjitKAKfSwfq4jkAM8Bt6vqwWh3i7At4tiDqi4EFkJoKCDaehnTGwjWW23SZ/KxioibUFBdoqrPx3D8nUDLJSqHAbti2N+YXk/9QUhwbzUd17LrS6KZFSDAY8AWVW1/Ml5ka4GRInIC8DVwDfD9mGtpTC9w0B/gb1UH2OP1Mdjj5pL8o+jvcoIz+rSFwcYAjoz2F2vUQBAcoWPZhbDUiWYo4ExgFrBJRCrC2/4vkAE8DOQBL4pIhapeKCLHEZpWNVNV/SIyF3iF0HSrx1X1o4S3wphu5G3wgQqqSjDYtJx1ywCmbXK8Prh9Nw99WUVd4Nvlr3/+2dfcenw+txUMjvrc4hI0EETCS4cHvQFoCqYiODzRrZBrkiuaWQFvE3msFGB5hPK7gJktnr8EvBRvBY1JJw11PtweJ06XAxFpZ9UBaV6VQER4cPtu5n+xu02pukCQ+V/sRoH/XRjd6q1NARXCKx94A4jLgXic1jtNI3bnlTGx0CBOV+d/NiKh4Frj8/PQlx1nrnp4RxW1/tjT74kI1Yf28/3/9U+cdNJJlo/1CMmqfzQssBoTg4wsD42N3qjKOhwO/lZ9oNXH/0jqgkFW7P4m5rpYPtb0ZYHVmBiIQ8jI8ERdvsobXYrBPT5fzHXpa/lYly5dSlFREWPGjOHOO+9s3n7zzTczceJERo8eza9+9atW+zz88MOMHz+eoqKi5tt5582bxwMPPNBcZsyYMc3ZsRLFAqsxSTTY446uXKYn5ilSfSkf665du7jzzjt5/fXXqaioYO3atfz1r38F4N5772XdunVs3LiRN998s1Xi6kGDBrF+/XpuvvnmVsE02SxtoDFJdEn+Ufz8s687HA7Idjq4NO+ohF586m35WNeuXcu0adPIy8sD4Ac/+AGrV6/miiuu4Omnn2bhwoX4/X4qKyvZvHkzxcXFAHznO98BYMKECTz/fCxT8LvGeqzGdMG3060i6+9ycuvxHa8OcOvx+eS6vp0mpf4gGgiiwY57sKNHj6a8vDzia/HkY92wYQMlJSVx5WOtqKigoqKCTz75hHnz5qGqTJ8+vXn75s2beeyxx9ocqykf69ChQ5k1a1a72a3aa88XX3zBAw88wMqVK9m4cSMXX3xxq/o3ZbZyOp3NOVtdLler962z9sbDAqsxSXZ74bHcecKxZDtb/7llOx3cdcKx3H7EVCtxOULTqoJK0BtoFVRUFQ2GpnL1pXyskydP5s0332Tv3r0EAgGWLl3K2WefzcGDB+nXrx8DBgxgz549vPzyy53WubCwsPk869ev54svvoipzdGwoQBjuiCaj++qyu0Fg7lhWB4rqg9Q1egjP8PNpXlHteqptjm2y4HwbTAVR/imgxan7K58rO3dxdVd+ViHDBnCb37zG8455xxUlZkzZ3L55ZcDUFJSwujRoxkxYkTz0ENHrrrqKp588knGjRvH6aef3qZOidBpPtZUsHyspidIRj7WdNWXb4+NJx+rDQUYkwBHdlDSscPSFX01qMbLhgKMSYAjA48Fovj1qXysxpi2+vJH5GRJp3ys8X7ysKEAY+KUmZnJvn37et3HfhOiquzbt4/MzMyY97UeqzFxGjZsGDt37qS6ujrVVTFJkpmZybBhw2LezwKrMXFyu92t7mAypokNBRhjTIJZYDXGmASzwGqMMQlmgdUYYxLMAqsxxiSYBVZjjEmwTgOriAwXkTdEZIuIfCQit4W3HyMiZSLyafj70e3sv11ENolIhYhYZhVjTK8XTY/VD/yrqp4GlAI/EZFRwF3ASlUdCawMP2/POao6rqNsMMYY01t0GlhVtVJV14cf1wJbgKHA5cDicLHFwBVJqqMxxvQoMY2xikghUAK8BwxW1UoIBV+gvfUnFHhVRMpFZHYHx54tIutEZJ3dImiM6cmiDqwikgM8B9yuqgdjOMeZqjoeuIjQMMLUSIVUdaGqTlTViU0LhhljTE8UVWAVETehoLpEVZuWOtwjIkPCrw8BqiLtq6q7wt+rgOVA24V3jDGmF4lmVoAAjwFbVPW3LV56Abgu/Pg64L8j7NtPRHKbHgMXAB92tdLGGJPOoumxngnMAs4NT5mqEJGZwHxguoh8CkwPP0dEjhORl8L7DgbeFpENwPvAi6r694S3whhj0kinaQNV9W1arQvZynkRyu8CZoYffw6M7UoFjTGmp7E7r4wxJsEssBpjTIJZYDXGmASzwGqMMQlmgdUYYxLMAqsxxiSYBVZjjEkwC6zGGJNgFliNMXFR1VbPvf5gimqSfiywGmNi5vUHCaUR+ZbHFQonew428M1hbyqqlTYssBpjYna40d/ua4P7Z3J0Pw913vbL9HYWWI0xMcvOcHZaJsvdeZneygKrMSZmgaB2WkZEaPAFuqE26ccCqzEmZgfrfVGVy+yjvVYLrMaYmLmdFjo6Yj8dY0zM/FEMBfRlFliNMTHLsB5rh+ynY4yJ2VH9POw91JjqaqQtC6zGmLi0t16TscBqjInTwJyMVFchbVlgNcZ0yaEO7sLqqzoNrCIyXETeEJEtIvKRiNwW3n6MiJSJyKfh70e3s/8MEflERD4TkbsS3QBjTGr5LPlKG9H0WP3Av6rqaUAp8BMRGQXcBaxU1ZHAyvDzVkTECSwALgJGAdeG9zXG9BJH9/Owu6Yh1dVIK50GVlWtVNX14ce1wBZgKHA5sDhcbDFwRYTdJwGfqernquoF/hLezxjTizT6++atq+2JaYxVRAqBEuA9YLCqVkIo+AL5EXYZCnzV4vnO8LZIx54tIutEZF11dXUs1TLGpFijDQe0EnVgFZEc4DngdlU9GO1uEbZFvGVDVReq6kRVnZiXlxdttYwxKXa40c/eWpvT2lJUgVVE3ISC6hJVfT68eY+IDAm/PgSoirDrTmB4i+fDgF3xV9cYk0521zTw1Td1/I+TBqW6KmklmlkBAjwGbFHV37Z46QXguvDj64D/jrD7WmCkiJwgIh7gmvB+xpgerrbBx7EDMjn12P6prkraiabHeiYwCzhXRCrCXzOB+cB0EfkUmB5+jogcJyIvAaiqH5gLvELootfTqvpREtphjOlGXn+Q2gabv9oeV2cFVPVt2r977bwI5XcBM1s8fwl4Kd4KGmPSz7aqQww7JivV1UhbdueVMSZmmR4nuZnuVFcjbVlgNcbEpN7rZ8iAzFRXI611OhRgjDEtZXksbHTGeqzGmA41+ALsPdRIgy/AgcNeVG31gM7Yvx5jTIf8gSCDwikC++rigLGyHqsxpl27vqknxy5SxcwCqzEmogN1Xo472qZUxcMCqzGmFVVl3fZ9HJXtSXVVeiwLrMaYVqprGzl1yIBUV6NHs4tXxphW8vvbHNWush6rMaYVr69vJK32B4L4A8nJI2s9VmNMK35VJBDE7ezd/S5XEtvXu39yxpiYqcKX++tSXY0ezQKrMaaVfhkuDjf6OdjgS3VVeiwLrMaYNk4enMv+Q7bcSrwssBpj2jhY7wOEhj5yISvR7OKVMaaNpilXu2vqGdw/k9AKTSZa1mM1xrTr2AFZfLQr2kWZTRMLrMaYDp2Un8O26tpUV6NHscBqjOlQpttJTb0tHBgLC6zGmE7lZtjlmFh0GlhF5HERqRKRD1tsGysia0Rkk4isEJGIC4uLyPZwmQoRWZfIihtjus+gnAxq6m1ea7Si6bE+Acw4Ytsi4C5VLQKWA3d0sP85qjpOVSfGV0VjTKod3c/D19/Up7oaPUangVVVVwP7j9h8CrA6/LgMuCrB9TLGpJFgUHHYwGHU4v1RfQhcFn58NTC8nXIKvCoi5SIyO85zGWNSzOEQBvbLSHU1eox4A+v1wE9EpBzIBbztlDtTVccDF4XLT23vgCIyW0TWici66urqOKtljEmWvNwM9hxsSHU1eoS4AquqfqyqF6jqBGApsK2dcrvC36sIjcVO6uCYC1V1oqpOzMvLi6daxpgkOyrLjc9vt7l2Jq7AKiL54e8O4OfAIxHK9BOR3KbHwAWEhhCMMT2Uy+lIah7T3iKa6VZLgTXAKSKyU0R+DFwrIluBj4FdwB/DZY8TkZfCuw4G3haRDcD7wIuq+vdkNMIY0z2cDrG8AVHodNavql7bzku/j1B2FzAz/PhzYGyXameMSTuN/gAZLmeqq5HWrE9vjImJBdXOWWA1xpgEs8BqjDEJZoHVGGMSzAKrMcYkmAVWY4xJMAusxhiTYBZYjTEmwSywGmNMgllgNcaYBLPAaowxCWaB1RhjEswCqzHGJJgFVmOMSTALrMYYk2AWWI0xJsEssBpj0oaqproKCWGB1RiTNnrLsi8WWI0xJsEssBpjTIJZYDXGmASzwGqMMQnWaWAVkcdFpEpEPmyxbayIrBGRTSKyQkT6t7PvDBH5REQ+E5G7EllxY4xJV9H0WJ8AZhyxbRFwl6oWAcuBO47cSUScwALgImAUcK2IjOpSbY0xpgfoNLCq6mpg/xGbTwFWhx+XAVdF2HUS8Jmqfq6qXuAvwOVdqKsxxvQI8Y6xfghcFn58NTA8QpmhwFctnu8Mb4tIRGaLyDoRWVddXR1ntYwxPUUgEEx1FZIm3sB6PfATESkHcgFvhDKRZvq2e1uFqi5U1YmqOjEvLy/OahljegqHo3fcDBCJK56dVPVj4AIAETkZuDhCsZ207skOA3bFcz5jTO/TW+6yiiSuHquI5Ie/O4CfA49EKLYWGCkiJ4iIB7gGeCHeihpjTE8RzXSrpcAa4BQR2SkiPyZ0hX8r8DGhXugfw2WPE5GXAFTVD8wFXgG2AE+r6kfJaYYxxqQPScdsMhMnTtR169aluhrGGBORiJSr6sT2Xrc7r4wxJsEssBpjTIJZYDXGmASzwGqMMQlmgdUYYxLMAqsxxiRYWk63EpFq4DCwN9V1SbJB9O429vb2gbWxt4i1jQWq2u6992kZWAFEZF1H88R6g97ext7ePrA29haJbqMNBRhjTIJZYDXGmARL58C6MNUV6Aa9vY29vX1gbewtEtrGtB1jNcaYniqde6zGGNMjWWA1xpgES3lgFZGrReQjEQmKyMQjXisOL7P9UXip7czw9gnh55+JyEOS5qnI22ujiBSKSL2IVIS/Hmnx2vdEZGN4v/tSU/PoxdnGa8Pv40YR+buIDEpN7aMTaxtFJLfFtgoR2SsiD6asAZ2I8z30iMhCEdkqIh+LSKSFRdNGnG1cJSKftHgtv9MTqWpKv4DTCK36ugqY2GK7C9gIjA0/Hwg4w4/fB84gtK7Wy8BFqW5HnG0sBD6MUH4g8CWQF36+GDgv1e1IcBtdQBUwKPz8PmBeqtuRyDZG2L8cmJrqdiSyfcC/A/eEHzua3s90/Yqzja3KRvMV15pXiaSqWyDi+jcXABtVdUO43L5wuSFAf1VdE37+JHAFoQCbljpoY3tGAFtVtWm52tcILTG+MvG1S4w42ijhr34isg/oD3yWnNolRhxtbCYiI4F84K0EVyth4mzf9cCp4f2DpPkdWl15D2OR8qGADpwMqIi8IiLrReT/hLcPJbRQYZMOl9XuAU4QkQ9E5E0RmRLe9hlwavjjiYvQP45IS4z3FG3aqKo+4GZgE6HlfUYBj6Wwjl0V6X1s6VpgmYa7QD1Qm/aJyFHh1/4j/Df6jIgMTl0Vu6yj9/CP4WGAX0Qz9NgtPVYReQ04NsJLP1PV/25nNxdwFnA6UAeslNBy2wcjlE35L2ucbawEjlfVfSIyAfiriIxW1W9E5GZgGRAE/kGoF5tSiWwjUE8osJYAnwMPA/8G3JP4mkcvwe9jy9/Va4BZCa5uzBL8HroIrb78jqr+i4j8C/AAKW5nEt7DH6jq1yKSCzxHqH1PdlSHbgmsqnp+HLvtBN5U1b0AElqkcDzwJ0JvZpO0WFY7njaqaiPQGH5cLiLbCPXU16nqCmAFgIjMBgIJrG5cEtxGCW/bBiAiTwN3Ja628Un0+wggImMBl6qWJ7Ku8Uhw+8oJdXqWh4s+A/w4QVWNWxL+Fr8Ob68VkT8Dk+gksKbzUMArQLGIZIc/Dp8NbFbVSqBWRErDXfIfAu39F0prIpInIs7w4xHASEK9t5ZLjB8NzAEWpaqeXdFBG78GRolIU4ag6YRW8+1xOnofw64FlqaibonQXvvCwxorgGnhoucBm1NSyS5qr40i4pLwbBURcQOXAB92esA0uEp3JaHeaSOwB3ilxWv/BHwUbsh9LbZPDG/bBvyB8B1k6frVXhsJXZD6CNgArAcubbHPUkK/pJuBa1LdhiS18SZCwXQjoT/QgaluR6LbGH79c+DUVNc/Se9hAbA6/B6uJPRxOuVtSVQbgX6EeuYbw6//nvDspI6+7JZWY4xJsHQeCjDGmB7JAqsxxiSYBVZjjEkwC6zGGJNgFliNMSbBLLAaY0yCWWA1xpgE+/+TRPOsSZkudgAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "\n",
    "gdf = geopandas.read_file(url_coral_reef)\n",
    "gdf.plot(\"sourcethm\", legend=True)\n",
    "#print(gdf[\"objectid\",\"sourcethm\",\"geometry\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "4dce84d1d0b0a2614014f50ddc754a85fcae7539a149decca85d87d7385cd97c"
  },
  "kernelspec": {
   "display_name": "Python 3.10.2 ('gps_project')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.2"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
